# 服务配置
listen:
  port: 8080
  readtimeout: 10
  writetimeout: 10


# seo站点
seo:
  title: 站点名称
  keywords: golang,java
  description: we-blog一个基于gin构建的博客

# datasource
datasource:
  host: localhost
  port: 3306
  user: root
  pwd: root
  dbname: blog
  idles: 10
  connections: 100
  table_prefix: blog_

# upload
upload:
  ImagePrefixUrl: http://127.0.0.1:8000
  ImageSavePath: upload/images/
  ImageMaxSize: 5 # MB
  ImageAllowExts: .jpg,.jpeg,.png
  RuntimeRootPath: runtime/

# redis
redis:
  Host: 127.0.0.1:6379
  Password:
  MaxIdle: 30
  MaxActive: 20
  IdleTimeout: 200